---
ID: "ce17d928-5461-4c5e-9cb1-0c95326600f2"
Parent: "cd2f9578-21e0-4b38-a978-f5f2ee622e4c"
Template: "cd2f9578-21e0-4b38-a978-f5f2ee622e4c"
Path: /sitecore/templates/Modules/Vertex AI Agent Builder/Settings/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241010T200531Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\superuser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
    - ID: "733ccafd-7a81-4681-b74f-e5450b2b5ecd"
      Hint: Branch
      Value: 0
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e060cc87-4af2-4ee6-b7a3-6aa3c76420ee"
    - ID: "b364199e-4848-4ed6-8df8-989ea540ead0"
      Hint: Location
      Value: global
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241010T220827Z
    - ID: "f0bbfe5b-c01e-46f7-bbe5-d1eb94dffa4d"
      Hint: Collection
      Value: default_collection
